todoapp/urls.py
from django.urls import path
from todoapp import views

app_name = 'todo'

urlpatterns = [
    path('logout',views.userlogout , name = 'userlogout'),
    path('login',views.userlogin , name = 'userlogin'),
    path('signup',views.usersignup , name = 'usersignup'),
]

todowo/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from todoapp import views

urlpatterns = [
    path('',views.index,name = 'index'),
    path('todoapp/', include('todoapp.urls')),
    path('admin/', admin.site.urls),
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

todoapp/models.py
from django.db import models

# Create your models here.

class Todo(models.Model):
    name = models.CharField(max_length = 100)
    memo = models.TextField()
    important = models.CheckConstraint()
    complete = models.BooleanField()
    date = models.DateTimeField()

todoapp/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from django.db import IntegrityError
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login,logout,authenticate

# Create your views here.
def index(request):
    return render(request,'todoapp/index.html')


def usersignup(request):
    if request.method == 'POST':
        if request.POST['password1']== request.POST['password2']:
            try:
                user =  User.objects.create_user(username = request.POST['username'],password = request.POST['password1'])
                user.save()
                login(request,user)
                return render(request,'todoapp/index.html',{'user':user})
            except IntegrityError:
                return render(request, 'todoapp/usersignup.html',{'form': UserCreationForm(),'error': 'Username alredy registered'})
        else:
            return render(request, 'todoapp/usersignup.html',{'form': UserCreationForm(),'error': 'Password has to be mached'})

    else:
        return render(request, 'todoapp/usersignup.html',{'form': UserCreationForm()})

def userlogout(request):
    logout(request)
    return redirect('index')


def userlogin(request):
    if request.method == 'POST':
        user =  authenticate(request, username = request.POST['username'], password = request.POST['password'])
        if user is None:
            return render(request, 'todoapp/userlogin.html',{'form': AuthenticationForm(),'error': 'Username and password did not matched'})
        else:
            login(request,user)
            return render(request,'todoapp/index.html',{'user':user})
    else:
        return render(request, 'todoapp/userlogin.html',{'form': AuthenticationForm()})

templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <title>TODOWO</title>
  </head>
  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="{% url 'index' %}">TODOWO</a>
        </div>
        <ul class="nav navbar-nav">
          <li class="active"><a href="{% url 'index' %}">Home</a></li>
          {% if user.is_authenticated %}
            <li>
              <a href="{% url 'todo:userlogout' %}">Logout</a>
              <!--<form action="{% url 'todo:userlogout' %}" method="post">
                {% csrf_token %}
                <button type="submit" name="button">Log out</button>
              </form>-->
            </li>
          {% else %}
            <li><a href="{% url 'todo:usersignup' %}">Sign Up</a></li>
            <li><a href="{% url 'todo:userlogin' %}">Login</a></li>
          {% endif %}
          <li><a href="{% url 'admin:index' %}">Admin</a></li>
        </ul>
      </div>
    </nav>
    <div class="container">
      {% block body %}
      {% endblock %}

    </div>

  </body>
</html>

templates/todoapp/index.html
{% extends 'base.html' %}
{% block body %}

<div class="jumbotron">
  {% if user.is_authenticated %}
  <h1>Weclome to TODOWO {{user.username}} </h1>
  <p>How are you today</p>
  {% else %}
  <h1>Weclome to TODOWO</h1>
  <p>Please Login or Sign Up For continue</p>
  {% endif %}
</div>

{% endblock %}

templates/todoapp/userlogin.html
{% extends 'base.html' %}
{% block body %}

<div class="jumbotron">
  <h3>{{error}}</h3>
  <form action="{% url 'todo:userlogin' %}" method="POST">
    {{form.as_p}}
    {% csrf_token %}
    <button type="submit" class="btn btn-primary" name="button">Login</button>
  </form>
</div>

{% endblock %}

templates/todoapp/usersignup.html
{% extends 'base.html' %}
{% block body %}

<div class="jumbotron">
  <h3>{{error}}</h3>
  <form action="{% url 'todo:usersignup' %}" method="POST">
    {{form.as_p}}
    {% csrf_token %}
    <button type="submit" class="btn btn-primary" name="button">Sign Up</button>
  </form>
</div>

{% endblock %}